name: Test Prober

on:
  workflow_dispatch:
    inputs:
      enable_staging:
        required: false
        default: false
        type: boolean

permissions:
  id-token: write
  contents: read
  packages: write
  issues: write

jobs:
  prober:
    uses: ./.github/workflows/reusable-prober.yml
    secrets:
      PAGERDUTY_INTEGRATION_KEY: "fake"
      sigstore_github_token: ${{ secrets.SIGSTORE_BOT_PAT }}
    permissions:
      id-token: write
      contents: read
      packages: write
      issues: write
    with:
      enable_staging: ${{ inputs.enable_staging }}
      rekor_url: "https://rekor.sigstage.dev"
      fulcio_url: "https://fulcio.sigstage.dev"
      oidc_url: "https://oauth2.sigstage.dev/auth"
      tuf_repo: "https://tuf-repo-cdn.sigstage.dev"
      tuf_preprod_repo: "https://tuf-repo-cdn.sigstage.dev"
      tuf_root_url: "https://tuf-repo-cdn.sigstage.dev/root.json"
      triggerPagerDutyTest: false
